server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/groupllfproject?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 12345678
mybatis:
  type-aliases-package: com.woniu.pojo
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true